### ISSUE TITLE
I can't start the selfbot.

### ISSUE THREAD

**Issue by DeveloperTJ** [Favna/Discord-Self-Bot#15]
When I try to start it with "yarn start", I get this:
`yarn run v1.3.2
$ yarn install
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
$ node src/app.js
module.js:515
    throw err;
    ^

Error: Cannot find module '/home/censored/Desktop/Discord-Self-Bot/src/auth.json'
    at Function.Module._resolveFilename (module.js:513:15)
    at Function.Module._load (module.js:463:25)
    at Module.require (module.js:556:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/reid/Desktop/Discord-Self-Bot/src/DiscordSelfBot.js:22:9)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

**Comment by Favna** [comment]
# [Read the wiki](https://github.com/Favna/Discord-Self-Bot/wiki/Installation-&-Setup#setting-up-authentication-files)
