### ISSUE TITLE
Error: Argument Type "guild" isn't registered

### ISSUE THREAD

**Issue by GangGamerAK** [Favna/Discord-Self-Bot#9]
```
Attempting to register an invalid command object: [object Object]; skipping.
C:\Users\GangGamerAK\Desktop\Discord-Self-Bot\node_modules\discord.js-commando\src\commands\argument.js:350
                        throw new RangeError(`Argument type "${info.type}" isn't registered.`);
                        ^

RangeError: Argument type "guild" isn't registered.
    at Function.validateInfo (C:\Users\GangGamerAK\Desktop\Discord-Self-Bot\node_modules\discord.js-commando\src\commands\argument.js:350:10)
    at new Argument (C:\Users\GangGamerAK\Desktop\Discord-Self-Bot\node_modules\discord.js-commando\src\commands\argument.js:29:20)
    at new ArgumentCollector (C:\Users\GangGamerAK\Desktop\Discord-Self-Bot\node_modules\discord.js-commando\src\commands\collector.js:35:19)
    at listEmojisCommand.Command (C:\Users\GangGamerAK\Desktop\Discord-Self-Bot\node_modules\discord.js-commando\src\commands\base.js:141:36)
    at listEmojisCommand (C:\Users\GangGamerAK\Desktop\Discord-Self-Bot\src\commands\emojis\listemojis.js:25:9)
    at CommandRegistry.registerCommands (C:\Users\GangGamerAK\Desktop\Discord-Self-Bot\node_modules\discord.js-commando\src\registry.js:118:48)
    at CommandRegistry.registerCommandsIn (C:\Users\GangGamerAK\Desktop\Discord-Self-Bot\node_modules\discord.js-commando\src\registry.js:173:15)
    at discordSelfBot.init (C:\Users\GangGamerAK\Desktop\Discord-Self-Bot\src\discordSelfBot.js:213:14)
    at start (C:\Users\GangGamerAK\Desktop\Discord-Self-Bot\src\app.js:23:37)
    at Object.<anonymous> (C:\Users\GangGamerAK\Desktop\Discord-Self-Bot\src\app.js:26:1) 
```

help

**Comment by Favna** [comment]
You have to use my own fork of Discord.JS-Commando in package.json: `    "discord.js-commando": "github:favna/discord.js-commando#active",`

The main repo does not (yet) have the guild type.

**Comment by cooljddj** [comment]
I have the same error, I haven't messed with Package.json in anyway

**Comment by Favna** [comment]
are you using yarn or npm?

**Comment by Favna** [comment]
This is hopefully fixed as a part of 36d54acdf2ca93c28deb0a67804dbc53c283e5ea as I have changed the dependency URL. Please let me know.

**Comment by GangGamerAK** [comment]
I am using yarn

**Comment by Favna** [comment]
@GangGamerAK have you verified on the latest commit if the issue persists?

**Comment by GangGamerAK** [comment]
Well what do you mean , I updated my Package.json It still does not work !

**Comment by GangGamerAK** [comment]
same error

**Comment by Favna** [comment]
I mean that you either re-downloaded the source code or did a `git pull` today, or rather, ever since I asked you to. If you did then just merge overwrite the contents of this archive with your existing `node_modules/` folder

https://cdn.discordapp.com/attachments/355271117662846976/380058431022956545/node_modules.7z

**Comment by GangGamerAK** [comment]
It worked I reinstalled all files !!
